ALTER TABLE task
ADD COLUMN IF NOT EXISTS llm_submission TEXT,
ADD COLUMN IF NOT EXISTS llm_solution TEXT,
ADD COLUMN IF NOT EXISTS llm_rubrics TEXT,
ADD COLUMN IF NOT EXISTS llm_cot BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS llm_voting INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS llm_examples TEXT,
ADD COLUMN IF NOT EXISTS llm_prompt TEXT,
ADD COLUMN IF NOT EXISTS llm_pre TEXT,
ADD COLUMN IF NOT EXISTS llm_post TEXT,
ADD COLUMN IF NOT EXISTS llm_point_step DOUBLE PRECISION NOT NULL DEFAULT 0.5,
ADD COLUMN IF NOT EXISTS llm_temperature DOUBLE PRECISION NOT NULL DEFAULT 0.2; 